# Generated by Django 3.2.4 on 2021-06-08 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drafter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafter', to=settings.AUTH_USER_MODEL)),
                ('in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_charge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
